final Map<String, int> countryMethodMap = {
  'Afghanistan': 3,
  'Albania': 3,
  'Algeria': 3,
  'American Samoa': 3,
  'Andorra': 3,
  'Angola': 3,
  'Anguilla': 3,
  'Antarctica': 3,
  'Antigua and Barbuda': 3,
  'Argentina': 3,
  'Armenia': 3,
  'Aruba': 3,
  'Australia': 3,
  'Austria': 3,
  'Azerbaijan': 3,
  'Bahamas': 3,
  'Bahrain': 3,
  'Bangladesh': 1,
  'Barbados': 3,
  'Belarus': 3,
  'Belgium': 3,
  'Belize': 3,
  'Benin': 3,
  'Bermuda': 3,
  'Bhutan': 3,
  'Bolivia, Plurinational State of': 3,
  'Bonaire, Sint Eustatius and Saba': 3,
  'Bosnia and Herzegovina': 3,
  'Botswana': 3,
  'Bouvet Island': 3,
  'Brazil': 3,
  'British Indian Ocean Territory': 3,
  'Brunei Darussalam': 3,
  'Bulgaria': 3,
  'Burkina Faso': 3,
  'Burundi': 3,
  'Cabo Verde': 3,
  'Cambodia': 3,
  'Cameroon': 3,
  'Canada': 2,
  'Cayman Islands': 3,
  'Central African Republic': 3,
  'Chad': 3,
  'Chile': 3,
  'China': 1,
  'Christmas Island': 3,
  'Cocos (Keeling) Islands': 3,
  'Colombia': 3,
  'Comoros': 3,
  'Congo': 3,
  'Congo, The Democratic Republic of the': 3,
  'Cook Islands': 3,
  'Costa Rica': 3,
  'Croatia': 3,
  'Cuba': 3,
  'Curaçao': 3,
  'Cyprus': 3,
  'Czechia': 3,
  "Côte d'Ivoire": 3,
  'Denmark': 3,
  'Djibouti': 3,
  'Dominica': 3,
  'Dominican Republic': 3,
  'Ecuador': 3,
  'Egypt': 5,
  'El Salvador': 3,
  'Equatorial Guinea': 3,
  'Eritrea': 3,
  'Estonia': 3,
  'Eswatini': 3,
  'Ethiopia': 3,
  'Falkland Islands (Malvinas)': 3,
  'Faroe Islands': 3,
  'Fiji': 3,
  'Finland': 3,
  'France': 3,
  'French Guiana': 3,
  'French Polynesia': 3,
  'French Southern Territories': 3,
  'Gabon': 3,
  'Gambia': 3,
  'Georgia': 3,
  'Germany': 3,
  'Ghana': 3,
  'Gibraltar': 3,
  'Greece': 3,
  'Greenland': 3,
  'Grenada': 3,
  'Guadeloupe': 3,
  'Guam': 3,
  'Guatemala': 3,
  'Guernsey': 3,
  'Guinea': 3,
  'Guinea-Bissau': 3,
  'Guyana': 3,
  'Haiti': 3,
  'Heard Island and McDonald Islands': 3,
  'Holy See (Vatican City State)': 3,
  'Honduras': 3,
  'Hong Kong': 3,
  'Hungary': 3,
  'Iceland': 3,
  'India': 1,
  'Indonesia': 11,
  'Iran, Islamic Republic of': 3,
  'Iraq': 4,
  'Ireland': 3,
  'Isle of Man': 3,
  'Israel': 3,
  'Italy': 3,
  'Jamaica': 3,
  'Japan': 3,
  'Jersey': 3,
  'Jordan': 4,
  'Kazakhstan': 3,
  'Kenya': 3,
  'Kiribati': 3,
  "Korea, Democratic People's Republic of": 3,
  'Korea, Republic of': 3,
  'Kuwait': 8,
  'Kyrgyzstan': 3,
  "Lao People's Democratic Republic": 3,
  'Latvia': 3,
  'Lebanon': 3,
  'Lesotho': 3,
  'Liberia': 3,
  'Libya': 3,
  'Liechtenstein': 3,
  'Lithuania': 3,
  'Luxembourg': 3,
  'Macao': 3,
  'Madagascar': 3,
  'Malawi': 3,
  'Malaysia': 11,
  'Maldives': 3,
  'Mali': 3,
  'Malta': 3,
  'Marshall Islands': 3,
  'Martinique': 3,
  'Mauritania': 3,
  'Mauritius': 3,
  'Mayotte': 3,
  'Mexico': 3,
  'Micronesia, Federated States of': 3,
  'Moldova, Republic of': 3,
  'Monaco': 3,
  'Mongolia': 3,
  'Montenegro': 3,
  'Montserrat': 3,
  'Morocco': 3,
  'Mozambique': 3,
  'Myanmar': 3,
  'Namibia': 3,
  'Nauru': 3,
  'Nepal': 3,
  'Netherlands': 3,
  'New Caledonia': 3,
  'New Zealand': 3,
  'Nicaragua': 3,
  'Niger': 3,
  'Nigeria': 3,
  'Niue': 3,
  'Norfolk Island': 3,
  'North Macedonia': 3,
  'Northern Mariana Islands': 3,
  'Norway': 3,
  'Oman': 4,
  'Pakistan': 1,
  'Palau': 3,
  'Palestine, State of': 3,
  'Panama': 3,
  'Papua New Guinea': 3,
  'Paraguay': 3,
  'Peru': 3,
  'Philippines': 3,
  'Pitcairn': 3,
  'Poland': 3,
  'Portugal': 3,
  'Puerto Rico': 3,
  'Qatar': 9,
  'Romania': 3,
  'Russian Federation': 3,
  'Rwanda': 3,
  'Réunion': 3,
  'Saint Barthélemy': 3,
  'Saint Helena, Ascension and Tristan da Cunha': 3,
  'Saint Kitts and Nevis': 3,
  'Saint Lucia': 3,
  'Saint Martin (French part)': 3,
  'Saint Pierre and Miquelon': 3,
  'Saint Vincent and the Grenadines': 3,
  'Samoa': 3,
  'San Marino': 3,
  'Sao Tome and Principe': 3,
  'Saudi Arabia': 4,
  'Senegal': 3,
  'Serbia': 3,
  'Seychelles': 3,
  'Sierra Leone': 3,
  'Singapore': 10,
  'Sint Maarten (Dutch part)': 3,
  'Slovakia': 3,
  'Slovenia': 3,
  'Solomon Islands': 3,
  'Somalia': 3,
  'South Africa': 3,
  'South Georgia and the South Sandwich Islands': 3,
  'South Sudan': 3,
  'Spain': 3,
  'Sri Lanka': 3,
  'Sudan': 3,
  'Suriname': 3,
  'Svalbard and Jan Mayen': 3,
  'Sweden': 3,
  'Switzerland': 3,
  'Syrian Arab Republic': 3,
  'Taiwan, Province of China': 3,
  'Tajikistan': 3,
  'Tanzania, United Republic of': 3,
  'Thailand': 3,
  'Timor-Leste': 3,
  'Togo': 3,
  'Tokelau': 3,
  'Tonga': 3,
  'Trinidad and Tobago': 3,
  'Tunisia': 3,
  'Turkey': 13,
  'Turkmenistan': 3,
  'Turks and Caicos Islands': 3,
  'Tuvalu': 3,
  'Uganda': 3,
  'Ukraine': 3,
  'United Arab Emirates': 12,
  'United Kingdom': 3,
  'United States': 2,
  'United States Minor Outlying Islands': 3,
  'Uruguay': 3,
  'Uzbekistan': 3,
  'Vanuatu': 3,
  'Venezuela, Bolivarian Republic of': 3,
  'Viet Nam': 3,
  'Virgin Islands, British': 3,
  'Virgin Islands, U.S.': 3,
  'Wallis and Futuna': 3,
  'Western Sahara': 3,
  'Yemen': 4,
  'Zambia': 3,
  'Zimbabwe': 3,
  'Åland Islands': 3,
};